notifications:
  email: false

git:
  depth: 3
  
env: 
  global:
    - pyv=3.5

matrix:
  include:
    - os: osx
      env: 
        - osv=MacOSX
      compiler: gcc

    - os: linux
      sudo: required
      dist: trusty
      env: 
        - osv=Linux
      addons:
        apt:
          packages:
            - gfortran


install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-$osv-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes --quiet conda
    - conda create --yes -n test python=$pyv
    - source activate test
    - pip -q install coveralls
    - python setup.py develop

script:
    - coverage run test/test.py

after_success:
    - coveralls
