language: python
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

matrix:
  include:
  - os: linux
    python: 3.6
    install:
    # temp workaround while waiting for PR
    - pip install -r requirements.txt

    - pip install -e .[tests,cov]
    script: 
    - flake8
    - mypy . --ignore-missing-imports
    after_success:
    - pytest --cov
    - coveralls
  - os: osx
    language: sh
    install: 
    # temp workaround while waiting for PR
    - pip3 install -r requirements.txt

    - pip3 install -e .[tests]
  - os: windows
    language: sh
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    
install: 
# temp workaround while waiting for PR
- pip install -r requirements.txt

- pip install -e .[tests]

script: pytest -rsv
