language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.6
 # - 3.7  FIXME h5py py37 wheel wait

os:
- linux

addons:
  apt:
    packages:
    - gfortran
    - libncurses-dev
      
before_install:
- python setup_spacepy.py > /dev/null
- . $HOME/cdf*dist/bin/definitions.B

# Fake X11 server
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to star


install: pip install -e .[tests,fov]

script:
- pytest -rsv
- flake8
- mypy . --ignore-missing-imports

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  pytest --cov;
  coveralls;
  fi

