language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gcc
      - make
      - gfortran
      - libncurses-dev
      
before_install:
  - wget https://spdf.sci.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/cdf-dist-all.tar.gz
  - tar xf cdf*-dist-all.tar.gz -C ~
  - cd $HOME/cdf*dist
  - make OS=linux ENV=gnu CURSES=yes FORTRAN=no UCOPTIONS=-O2 SHARED=yes all
  - make install 
  - . $HOME/cdf-dist/bin/definitions.B
      

install: python -m pip install -e .[tests]

script: coverage run tests/test_all.py -v

after_success: coveralls

