language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest

git:
  depth: 3

addons:
  apt:
    packages:
      - gcc
      - make
      - gfortran
      - libncurses-dev
      
before_install:
  - python setup_spacepy.py
  - . $HOME/cdf*dist/bin/definitions.B


install: python -m pip install -e .[tests]

script: coverage run tests/test_all.py -v

after_success: coveralls

