language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest

git:
  depth: 3

addons:
  apt:
    packages:
      - gcc
      - make
      - gfortran
      - libncurses-dev
      
before_install:
  - python setup_spacepy.py
  - . $HOME/cdf*dist/bin/definitions.B


install: pip install -e .[tests]

script: 
  - pytest -v
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    coverage run tests/test_all.py;
    coveralls;
    fi

