language: python
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.6

os:
- linux

install:
- cd ..
- git clone https://github.com/scivision/cdflib
- cd cdflib
- pip install -e .
- cd $TRAVIS_BUILD_DIR

- pip install -e .[tests]

script:
- pytest -rsv
- flake8
- mypy . --ignore-missing-imports

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  pytest --cov --cov-config=setup.cfg;
  coveralls;
  fi

