language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
  - 3.6
 # - 3.7  FIXME h5py py37 wheel wait

os:
  - linux

addons:
  apt:
    packages:
      - gcc
      - make
      - gfortran
      - libncurses-dev
      
before_install:
  - python setup_spacepy.py > /dev/null
  - . $HOME/cdf*dist/bin/definitions.B


install: pip install -e .[tests,fov]

script:
  - pytest -sv
  - flake8
  # - mypy . --ignore-missing-imports  # relax for new mypy version

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

