language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

matrix:
  include:
  - os: linux
    python: 3.7
    install:
    - pip install -r requirements.txt
    - pip install -e .[tests,lint]
    script:
    - flake8
    - mypy .
    after_success:
    - pytest --cov

install: pip install -e .[tests]

script: pytest -r a -v
